name: Rust

on:
  workflow_dispatch:
  create:
    tags:
      - 'deploy'
    
env:
  SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
  SERVER: ${{ env.SERVER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  USER: ${{ env.USER }}
  DATABASE_URL: ${{ env.DATABASE_URL }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache target directory
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-target-release-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: bash ./crate/receiver/script/semi-auto-deploy.sh
