name: Rust

on:
  workflow_dispatch:
    
jobs:
  deployment:

    runs-on: ubuntu-latest
    
    environment: deploy_loader

    steps:
    - uses: actions/checkout@v3

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache target directory
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-target-release-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: bash ./crate/receiver/script/semi-auto-deploy.sh
