name: full_deploy

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_ADDRESS: ${{ secrets.MAIN_SERVER_ADDRESS }}
  SSH_USER_PASSWORD: ${{ secrets.PIH_PAH_PASSWORD }}
  SSH_USER: ${{ secrets.PIH_PAH_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo bin
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-target-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Run deploy script
        run: ls

      - name: Install ALSA development libraries
        run: sudo apt-get install -y libasound2-dev

      - name: Run deploy script
        run: bash ${{ vars.LOAD_BALANCER_DEPLOY_SCRIPT_PATH }}
        
      - name: Run deploy script
        run: bash ${{ vars.RECIVER_DEPLOY_SCRIPT_PATH }}
        
      - name: Run deploy script
        run: bash ${{ vars.SERVER_DEPLOY_SCRIPT_PATH }}
